//! Diagnostics vs. the committed blackjax reference fixture
//! (generated by scripts/generate_diagnostics_fixture.py).

use jaxstanv5_core::diagnostics::{effective_sample_size, potential_scale_reduction};
use jaxstanv5_core::json::{self, Value};

fn fixture() -> Value {
    let path = format!(
        "{}/tests/data/diagnostics_fixture.json",
        env!("CARGO_MANIFEST_DIR")
    );
    json::parse(&std::fs::read_to_string(path).expect("fixture readable")).expect("parses")
}

fn rel_close(got: f64, want: f64, rtol: f64) -> bool {
    (got - want).abs() <= rtol * want.abs()
}

#[test]
fn rhat_and_ess_match_blackjax() {
    let doc = fixture();
    let cases = doc.get("cases").and_then(Value::as_array).expect("cases");
    assert!(!cases.is_empty());
    for case in cases {
        let name = case.get("name").and_then(Value::as_str).unwrap();
        let chains: Vec<Vec<f64>> = case
            .get("chains")
            .and_then(Value::as_array)
            .unwrap()
            .iter()
            .map(|chain| {
                chain
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|v| v.as_f64().unwrap())
                    .collect()
            })
            .collect();

        let want_ess = case.get("ess").and_then(Value::as_f64).unwrap();
        let got_ess = effective_sample_size(&chains);
        // Direct autocovariance vs FFT: identical estimator, different
        // rounding; 1e-8 relative is orders of magnitude above the noise.
        assert!(
            rel_close(got_ess, want_ess, 1e-8),
            "{name}: ess {got_ess} != {want_ess}"
        );

        if let Some(want_rhat) = case.get("rhat").and_then(Value::as_f64) {
            let got_rhat = potential_scale_reduction(&chains);
            assert!(
                rel_close(got_rhat, want_rhat, 1e-10),
                "{name}: rhat {got_rhat} != {want_rhat}"
            );
        }
    }
}
