//! Special functions vs. the committed mpmath reference table.
//!
//! The table is generated by `scripts/generate_special_fn_table.py` (400-digit
//! mpmath, rounded to f64) and committed; regenerating it is a deliberate act.

use jaxstanv5_core::json::{self, Value};
use jaxstanv5_core::special;

fn table() -> Value {
    let path = format!(
        "{}/tests/data/special_fn_table.json",
        env!("CARGO_MANIFEST_DIR")
    );
    json::parse(&std::fs::read_to_string(path).expect("table exists")).expect("table parses")
}

fn check(name: &str, f: impl Fn(f64) -> f64, rtol: f64, atol: f64) {
    let table = table();
    let entries = table.get(name).and_then(Value::as_array).expect("entries");
    assert!(!entries.is_empty());
    for entry in entries {
        let pair = entry.as_array().expect("pair");
        let x = pair[0].as_f64().unwrap();
        let want = pair[1].as_f64().unwrap();
        let got = f(x);
        let tol = atol + rtol * want.abs();
        assert!(
            (got - want).abs() <= tol,
            "{name}({x}) = {got:e}, want {want:e} (err {:e}, tol {tol:e})",
            (got - want).abs()
        );
    }
}

#[test]
fn gammaln_matches_reference() {
    // Lanczos g=7 n=9 is good to ~1e-14 relative on the positive axis; the
    // atol absorbs the exact zeros at x=1 and x=2.
    check("gammaln", special::gammaln, 1e-13, 1e-13);
}

#[test]
fn digamma_matches_reference() {
    // atol absorbs the root near x=1.4616 where relative error is undefined.
    check("digamma", special::digamma, 1e-13, 1e-13);
}

#[test]
fn erf_matches_reference() {
    check("erf", special::erf, 1e-13, 1e-15);
}

#[test]
fn erfc_matches_reference() {
    // Cephes erfc loses a couple of digits deep in the right tail (the
    // exp(-x*x) factor alone costs ~x^2 ulp); 5e-12 covers x=26.5 with margin.
    check("erfc", special::erfc, 5e-12, 1e-300);
}

#[test]
fn ndtr_matches_reference() {
    check("ndtr", special::ndtr, 5e-12, 1e-300);
}

#[test]
fn ndtri_matches_reference() {
    // Cephes ndtri peak relative error is ~1e-13 in the central region and
    // grows slowly in the far tail expansion; 5e-12 holds down to p=1e-300.
    check("ndtri", special::ndtri, 5e-12, 0.0);
}

#[test]
fn xlogy_handles_zero_times_log_zero() {
    assert_eq!(special::xlogy(0.0, 0.0), 0.0);
    assert_eq!(special::xlogy(0.0, 5.0), 0.0);
    let got = special::xlogy(3.0, 2.0);
    assert!((got - 3.0 * 2.0_f64.ln()).abs() < 1e-15);
}

#[test]
fn sigmoid_and_softplus_are_stable() {
    assert!((special::sigmoid(0.0) - 0.5).abs() < 1e-16);
    assert!((special::sigmoid(709.0) - 1.0).abs() < 1e-16);
    assert!(special::sigmoid(-745.0) > 0.0);
    assert!((special::softplus(0.0) - 2.0_f64.ln()).abs() < 1e-16);
    // softplus(x) -> x for large x, exactly representable here.
    assert_eq!(special::softplus(1000.0), 1000.0);
    assert!((special::softplus(-20.0) - (-20.0_f64).exp().ln_1p()).abs() < 1e-22);
}

#[test]
fn ndtri_boundaries() {
    assert_eq!(special::ndtri(0.0), f64::NEG_INFINITY);
    assert_eq!(special::ndtri(1.0), f64::INFINITY);
    assert!(special::ndtri(-0.1).is_nan());
    assert!(special::ndtri(1.1).is_nan());
}
